##
## Executes commands at login pre-zshrc.
##

echo now executing ~/.zprofile

##
## Browser
##

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

##
## Editors
##

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

##
## Language
##

if [[ -z "$LANG" ]]; then
  export LANG='en_GB.UTF-8'
fi

##
## Paths
##

# Go
export GOPATH=/Users/john/gocode

# Python
export PYTHONPATH=$(brew --prefix)/lib/python2.7/site-packages

## Set the list of directories that Zsh searches for programs.

## Ensure path arrays do not contain duplicates.
typeset -gU CDPATH FPATH MAILPATH PATH

path=(
  /usr/local/bin  # This should be first in the path, but homebrew wants it to be after /usr/bin to run apple standard (usr/bin) files before custom ones.  May break things if kept in this order. - JGB
  /usr/bin
  /bin
  /usr/sbin
  /sbin
  # /usr/local/Cellar/go/1.4.2/libexec/bin  # Path to go used in Homebrew.  Here to get GoConvey working. - JGB
  $HOME/go_appengine                             #added 04/04/2014 for Go Appengine SDK
  ${GOPATH//://bin:}/bin                         # add all $GOPATH/bin directories to the path
  $HOME/.rvm/bin                                 # Add RVM (Ruby Version Manager) to PATH for scripting
  $HOME/.scripts
  /Users/john/Library/Android/sdk/platform-tools # JGB 29-09-2016 Added to get github.com/JakeWharton/pidcat working
  /Users/john/Library/Android/sdk/tools          # JGB 29-09-2016 Added to get github.com/JakeWharton/pidcat working
  $PATH
)

# Set the the list of directories that cd searches.
# cdpath=(
#  $cdpath
#  /gocode/src/github.com
#)

##
## Less
##

# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

##
## Temporary Files
##

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$USER"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"
if [[ ! -d "$TMPPREFIX" ]]; then
  mkdir -p "$TMPPREFIX"
fi
